### ISSUE TITLE
SyntaxError: f-string: unmatched '('

### ISSUE THREAD

**Issue by Root-FTW** [Sneezedip/Tiktok-Booster#11]
Microsoft Windows [Version 10.0.22631.4169]
(c) Microsoft Corporation. All rights reserved.

C:\Users\rootf\Downloads\Compressed\Tiktok-Booster-2.7.3\Tiktok-Booster-2.7.3>main.py
Traceback (most recent call last):
  File "C:\Users\rootf\Downloads\Compressed\Tiktok-Booster-2.7.3\Tiktok-Booster-2.7.3\main.py", line 9, in <module>
    from Modules.Usage import ProgramUsage
  File "C:\Users\rootf\Downloads\Compressed\Tiktok-Booster-2.7.3\Tiktok-Booster-2.7.3\Modules\Usage.py", line 158
    response = requests.get(f"https://sneezedip.pythonanywhere.com/get_key?uuid={UUID.split("-")[4]}").json()
                                                                                             ^
SyntaxError: f-string: unmatched '('

C:\Users\rootf\Downloads\Compressed\Tiktok-Booster-2.7.3\Tiktok-Booster-2.7.3>

**Comment by Sneezedip** [comment]
This is because your python version is below 3.12.. 
Install python 3.12

**Comment by CookiesKush** [comment]
> This is because your python version is below 3.12.. Install python 3.12

It might be a good idea to include that in the README.
