### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emil030303** [Sneezedip/Tiktok-Booster#14]
Tiktok-Booster-2.7.3.3 % python3.12 main.py
Installing Libraries...
Requirement already satisfied: selenium~=4.23.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (4.23.1)
Requirement already satisfied: pytesseract~=0.3.13 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.3.13)
Requirement already satisfied: pillow~=10.4.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (10.4.0)
Requirement already satisfied: fake_headers in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: colorama~=0.4.6 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: discordwebhook~=1.0.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.0.3)
Requirement already satisfied: fake_useragent in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (1.5.1)
Requirement already satisfied: tqdm~=4.66.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (4.66.5)
Requirement already satisfied: requests~=2.32.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.32.3)
Requirement already satisfied: bs4~=0.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (0.0.2)
Requirement already satisfied: beautifulsoup4~=4.12.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (4.12.3)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium~=4.23.1->-r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium~=4.23.1->-r requirements.txt (line 1)) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium~=4.23.1->-r requirements.txt (line 1)) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium~=4.23.1->-r requirements.txt (line 1)) (2024.2.2)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium~=4.23.1->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium~=4.23.1->-r requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: packaging>=21.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pytesseract~=0.3.13->-r requirements.txt (line 2)) (24.1)
Requirement already satisfied: html5lib in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from fake_headers->-r requirements.txt (line 4)) (1.1)
Requirement already satisfied: importlib-resources>=5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from fake_useragent->-r requirements.txt (line 7)) (6.4.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests~=2.32.3->-r requirements.txt (line 9)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests~=2.32.3->-r requirements.txt (line 9)) (3.6)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from beautifulsoup4~=4.12.3->-r requirements.txt (line 11)) (2.5)
Requirement already satisfied: zipp>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from importlib-resources>=5.0->fake_useragent->-r requirements.txt (line 7)) (3.20.2)
Requirement already satisfied: attrs>=23.2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio~=0.17->selenium~=4.23.1->-r requirements.txt (line 1)) (23.2.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio~=0.17->selenium~=4.23.1->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio~=0.17->selenium~=4.23.1->-r requirements.txt (line 1)) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio~=0.17->selenium~=4.23.1->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: exceptiongroup in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio~=0.17->selenium~=4.23.1->-r requirements.txt (line 1)) (1.2.2)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium~=4.23.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium~=4.23.1->-r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from html5lib->fake_headers->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from html5lib->fake_headers->-r requirements.txt (line 4)) (0.5.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium~=4.23.1->-r requirements.txt (line 1)) (0.14.0)
Libraries installed. Restart the program!

**Comment by Sneezedip** [comment]
thats not an error...
